### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by kobebryantwx** [shubowen/VerticalRollingTextView#5]
Attempt to invoke virtual method 'int com.xiaosu.DataSetAdapter.getItemCount()' on a null object reference
com.xiaosu.VerticalRollingTextView.animationEnd(VerticalRollingTextView.java:144)

**Comment by shubowen** [comment]
是怎么出现这种情况的？

**Comment by kobebryantwx** [comment]
bugly报的，具体操作不知道。

**Comment by shubowen** [comment]
你用的是什么版本，试一下最新的版本看看

**Comment by kobebryantwx** [comment]
最新版，monkey测试跑出来的。
