### ISSUE TITLE
想固定字体大小并且不换行

### ISSUE THREAD

**Issue by hnty545** [shubowen/VerticalRollingTextView#9]
我想固定字体大小为14sp并且不换行，设置了这2个属性
android:ellipsize="end"
android:maxLines="1"
但在SingleLineStrategy的getLayout里BoringLayout.isBoring返回null，new BoringLayout这行报了空指针，请问如何满足以上需求

另外我在想在以上maxLines=1的情况下，如何根据控件渲染宽度和字体来自动断句，比如输入一行很长的文本，自动断为几行文本，在DataSetAdapter的构造方法和setData时处理他。

**Comment by shubowen** [comment]
已经修复。自动断句的需求是什么？

**Comment by hnty545** [comment]
好的谢谢，我做了一个工具方法，等会发上来。就是根据字体和控件宽度，把一段话分成n段。因为有些业务场景要求我分段显示并且滚屏。

**Comment by hnty545** [comment]
int num = vrtv_message.getMeasuredWidth() / AppUtil.sp2px(HomeActivity.this, 14);
List<CharSequence> sequences = AppUtil.splitCharSequence(HomeActivity.this.sequences, num);

——————
public static List<CharSequence> splitCharSequence(List<CharSequence> _data, int maxNum) {
        if (_data == null || _data.size() == 0) {
            return _data;
        }
        List<CharSequence> data = new ArrayList<>();
        for (CharSequence charSequence : _data) {
            int i = 0;
            if (charSequence.length() > maxNum) {
                int start = 0;
                int end = 0;
                for (i = 0; end < charSequence.length(); i++) {
                    start = i * maxNum;
                    end = (i + 1) * maxNum;
                    if (end > charSequence.length()) {
                        end = charSequence.length();
                    }
                    data.add(charSequence.subSequence(start, end));
                }
            }
        }
        return data;
    }

**Comment by Rianney** [comment]
不能通过textSize控制字体大小 只能通过设置layout_height 实际高度来控制字体大小 然后添加到父容器里面
